---
- name: Install docker Centos
  gather_facts: No
  hosts: all
  become: yes
  user: root

  tasks:
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest

    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest

    - name: Install lvm2
      yum:
        name: lvm2
        state: latest

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      become: yes

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docker-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes

    - name: Enable Docker Test repo
      ini_file:
        dest: /etc/yum.repos.d/docker-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0
      become: yes
      
    - name: Add epel-release repo
      yum:
       name: epel-release
       state: present  

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Install Docker Compose
      package:
        name: docker-compose
        state: latest
      become: yes

    - name: Install packages
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - bash-completion
        - nano
        - mc
        - vim 
      become: yes


    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Add user vagrant to docker group
      user:
        name: vagrant
        groups: docker
        append: yes
      become: yes

    - name: Utilizando modulo lineinfile para modificar la configuracion de selinux
      lineinfile: path=/etc/sysconfig/selinux regexp="^SELINUX=" line="SELINUX=disabled"

    - name: Stop and disabled firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no
...        
